name: docker_image_building_evaluating_process
on:
  push:
    branches:
      - dev

jobs:

  build-and-publish:

    ###### dockerhub logging ######
    runs-on:
      # - ubuntu-latest
      # - nchc
      # - cindy
      # - poca
      - hope
    if: github.ref == 'refs/heads/dev'

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_ACCOUNT }}
        password: ${{ secrets.DOCKER_PASSWD }}

    ###### clearning github layers process ######
    # 有一些layers透過shell執行，有改變時不會被docker捕捉到，work round
    # 的方法是強迫更新layers以後再往上推。這邊先用hello-world作為強迫更
    # 新的image代表。
    - run: docker pull hello-world
    - run: docker pull markliou/dl-container:temp
    - run: docker rmi -f markliou/dl-container:temp
    - run: docker tag hello-world markliou/dl-container:temp
    - run: docker push markliou/dl-container:temp


    ###### building process ######
    - name: dl-container
      uses: docker/build-push-action@v5
      with:
        context: ./dl-container/GPU/
        # file: ./dl-container/GPU/Dockerfile
        push: True
        tags: markliou/dl-container:temp
        no-cache: True
