name: Docker image evaluating process
on:
  push:
    branches:
      - dev

jobs:

  build-and-publish:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_ACCOUNT }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: get the current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    ###### building process ######
    - name: dl-container
      uses: docker/build-push-action@v5
      with:
        context: ./dl-container/GPU/
        # file: ./dl-container/GPU/Dockerfile
        push: False
        tags: markliou/dl-container:temp
