name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_ACCOUNT }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: python3-tensorflow-gpu
      uses: docker/build-push-action@v2
        with:
          # context: ./python3-tensorflow-gpu/GPU/.
          file: ./python3-tensorflow-gpu/GPU/Dockerfile
          push: True
          tags: markliou/actionpush