name: Docker image building process

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ACCOUNT }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: get the current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    ###### building process ######
    - name: python3-tensorflow-gpu
      uses: docker/build-push-action@v5
      with:
        context: ./python3-tensorflow-gpu/GPU/
        # file: ./python3-tensorflow-gpu/GPU/Dockerfile
        push: True
        tags: markliou/python3-tensorflow-gpu markliou/python3-tensorflow-gpu:${{ steps.date.outputs.date }}

    # - name: python3-tensorflow-gpu:cpu
      # uses: docker/build-push-action@v2
      # with:
        # context: ./python3-tensorflow-gpu/CPU/
        # # file: ./python3-tensorflow-gpu/GPU/Dockerfile
        # push: True
        # tags: markliou/python3-tensorflow-gpu:cpu

    - name: docker-in-docker
      uses: docker/build-push-action@v2
      with:
        context: ./dind/
        # file: ./python3-tensorflow-gpu/GPU/Dockerfile
        push: True
        tags: markliou/dind

    # - name: spark:latest
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./spark/
    #     # file: ./python3-tensorflow-gpu/GPU/Dockerfile
    #     push: True
    #     tags: markliou/spark:latest
