name: docker_image_publishing_process

# main branch for publishing
on:
  push:
    branches:
      - master
      - '!dev'
  # pull_request:
  #   branches: [ master ]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_ACCOUNT }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: get the current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    ###### building process ######
    # - name: dl-container
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: ./dl-container/GPU/
    #     # file: ./dl-container/GPU/Dockerfile
    #     push: True
    #     tags: markliou/dl-container:latest , markliou/dl-container:${{ steps.date.outputs.date }}

    - name: docker-in-docker
      uses: docker/build-push-action@v5
      with:
        context: ./dind/
        push: True
        tags: markliou/dind

    # - name: spark:latest
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./spark/
    #     # file: ./python3-tensorflow-gpu/GPU/Dockerfile
    #     push: True
    #     tags: markliou/spark:latest


