name: dl_container_gpu_test

# main branch for publishing
on:
  workflow_run:
    workflows:
      # - docker_image_building_evaluating_process
      - docker_image_publishing_process
    branches:
      - master
      # - dev
    types:
      - completed

jobs:
  # checkout:
  #   runs-on:
  #     - gpu
  #   steps:
  #     - name: gpu_test
  #       uses: actions/checkout@v4

  # dev_dl-container_test:
  #   runs-on:
  #     # - cindy
  #     - gpu
  #   steps:
  #     - run: docker pull markliou/dl-container:temp
  #     - run: docker run --rm --gpus all markliou/dl-container:temp gpu_test

  published_dl-container_test:
    runs-on:
      # - cindy
      - poca
    steps:
      - run: docker pull markliou/dl-container:latest
      - run: docker tag markliou/dl-container:latest markliou/dl-container:t
      - run: docker rmi -f markliou/dl-container:latest markliou/dl-container:t
      - run: docker run --rm --gpus all markliou/dl-container:latest gpu_test
      - run: docker rmi -f markliou/dl-container:latest

  published_dind_test:
    runs-on:
      - cindy
      # - gpu
    steps:
      - run: python3 -c "import subprocess ; subprocess.run('docker pull markliou/dind', shell=True) ; subprocess.check_call('docker run -d --rm --name tst markliou/dind', shell=True) ; subprocess.run('docker stop tst', shell=True)"
